# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: App Deployment

on:
  push:
    branches: [ "main" ] # only execute the job when merge happens with the main branch


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4    # tells github to checkout the repository to the feature/main branch
    - name: Build Image
      run: docker build -t tridevg/nextjs-app:${{ github.sha }} .    # builds the docker image locally
    - name: Tag Image
      run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin    # login to docker hub using github secrets
    - name: Push Image
      run: |
        docker push tridevg/nextjs:latest
        docker push tridevg/nextjs-app:${{ github.sha }}    # pushes the local docker image to docker hub repository 
    - name: Deploy to Server
      run: echo "Deployed to Server..."